server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi-RegisterUser
          uri: http://localhost:8081/api/v1/registerUser/
          predicates:
            - Path=/api/v1/registerUser/

        - id: userCmdApi-UpdateUser
          uri: http://localhost:8081/api/v1/updateUser/**
          predicates:
            - Path=/api/v1/updateUser/**

        - id: userCmdApi-RemoveUser
          uri: http://localhost:8081/api/v1/removeUser/**
          predicates:
            - Path=/api/v1/removeUser/**

        - id: userQueryApi
          uri: http://localhost:8082/api/v1/userLookup/**
          predicates:
            - Path=/api/v1/userLookup/**

        - id: bankAccCmd-OpenAccount
          uri: http://localhost:1991/api/v1/open-bank-account/
          predicates:
            - Path=/api/v1/open-bank-account/

        - id: bankAccCmd-DepositFund
          uri: http://localhost:1991/api/v1/bank-account-funds-deposit/**
          predicates:
            - Path=/api/v1/bank-account-funds-deposit/**

        - id: bankAccCmd-WithDrawFund
          uri: http://localhost:1991/api/v1/bank-account-withdraw-funds/**
          predicates:
            - Path=/api/v1/bank-account-withdraw-funds/**

        - id: bankAccCmd-closeAccount
          uri: http://localhost:1991/api/v1/close-bank-account/**
          predicates:
            - Path=/api/v1/close-bank-account/**

        - id: bankAccQueryAPI
          uri: http://localhost:1992/api/v1/bankacc-lookup/**
          predicates:
            - Path=/api/v1/bankacc-lookup/**